//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class subject
    {
        public int id { get; set; }

        [Display(Name = "Mã môn học")]
        [Required(ErrorMessage ="Chưa nhập mã môn học")]
        public string subject_id { get; set; }

        [Display(Name = "Tên môn học")]
        [Required(ErrorMessage = "Chưa nhập tên môn học")]
        public string name { get; set; }
    }
}
